import { defineField, defineType } from "sanity";
import { STATUS_OPTIONS, GRID_SIZE_OPTIONS } from "../shared/options";

export default defineType({
  name: "product",
  title: "Product",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "media", title: "Images" },
    { name: "meta", title: "Display" },
  ],
  fields: [
    defineField({ name: "name", type: "string", group: "content", validation: (Rule) => Rule.required() }),
    defineField({
      name: "slug",
      type: "slug",
      group: "content",
      options: { source: "name", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "category",
      type: "reference",
      to: [{ type: "productCategory" }],
      group: "content",
      description: "Drives both the product's badge and the Products nav dropdown grouping — pick from the fixed category list rather than typing free text.",
      validation: (Rule) => Rule.required(),
    }),
    defineField({ name: "tagline", type: "string", group: "content", validation: (Rule) => Rule.required() }),
    defineField({
      name: "status",
      type: "string",
      group: "content",
      options: { list: STATUS_OPTIONS, layout: "radio" },
      initialValue: "concept",
      description: "Shown as a status badge on every grid tile and detail page — keep this honest.",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "description",
      type: "text",
      rows: 3,
      group: "content",
      description: "Shown in the hero and grid previews.",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "problem",
      type: "text",
      rows: 3,
      group: "content",
      description: "\"The Problem\" section — the large editorial statement on the detail page.",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "idea",
      type: "text",
      rows: 2,
      group: "content",
      description: "\"The Idea\" section — the emotional turn of the story, keep this short.",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "howItWorks",
      title: "How it works",
      type: "array",
      group: "content",
      of: [{ type: "howItWorksStep" }],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: "features",
      title: "Key features",
      type: "array",
      group: "content",
      of: [{ type: "featureItem" }],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: "technologies",
      title: "Technology (grouped)",
      type: "array",
      group: "content",
      of: [{ type: "techGroup" }],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: "useCases",
      title: "Use cases",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: "roadmap",
      title: "Future roadmap",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "images",
      type: "projectImages",
      group: "media",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "size",
      title: "Grid tile size",
      type: "string",
      group: "meta",
      options: { list: GRID_SIZE_OPTIONS, layout: "radio" },
      initialValue: "standard",
      description: "Controls how large this product's tile appears in ShowcaseGrid / ProductStack.",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "featured",
      type: "boolean",
      group: "meta",
      initialValue: false,
      description: "Featured products can be pulled into homepage sections first.",
    }),
    defineField({
      name: "order",
      title: "Display order",
      type: "number",
      group: "meta",
    }),
  ],
  orderings: [
    { title: "Display order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] },
  ],
  preview: {
    select: { title: "name", subtitle: "tagline", status: "status", media: "images.thumbnail.image" },
    prepare({ title, subtitle, status, media }) {
      return { title: `${title}  ·  ${status}`, subtitle, media };
    },
  },
});
